
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: production
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:postgres123@postgres.production.svc.cluster.local:5432/mydb"
  FRONTEND_URL : "http://localhost:3001"
  PORT : "3000"
  JWT_EXPIRE_DAYS : "12"
  JWT_SECRET : "Asdfas"
  AWS_REGION : "ap-south-1"
  AWS_SECRET_ACCESS_KEY : "HiydRMTN3BG3BvG6/M"
  AWS_ACCESS_KEY_ID : "AKIAQUTQQU7HL"
  S3_BUCKET_NAME : "photo-search-image"
