
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: production
type: Opaque
stringData:
  DATABASE_CLIENT : "xxxxxxx"
  DATABASE_WRITE_HOST : "xxxxxxx"
  DATABASE_WRITE_PORT : "xxxxxxx"
  DATABASE_WRITE_USERNAME : "xxxxxxx"
  DATABASE_WRITE_PASSWORD : "xxxxxxx"
  DATABASE_WRITE_NAME : "xxxxxxx"
  DATABASE_READ_HOST : "xxxxxxx"
  DATABASE_READ_PORT : "xxxxxxx"
  DATABASE_READ_USERNAME : "xxxxxxx"
  DATABASE_READ_PASSWORD : "xxxxxxx"
  DATABASE_READ_NAME : "xxxxxxx"
  DATABASE_POOL_MIN : "xxxxxxx"
  DATABASE_POOL_MAX : "xxxxxxx"
  PORT : "xxxxxxx"
  AWS_REGION : "xxxxxxx"
  AWS_ACCESS_KEY_ID : "xxxxxxx"
  AWS_SECRET_ACCESS_KEY : "xxxxxxx"
  S3_BUCKET : "xxxxxxx"
  JWT_SECRET : "xxxxxxx"

