apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: space-bin
  namespace: production
spec:
  ingressClassName: nginx

  defaultBackend:
    service:
      name: backend-service
      port:
        number: 80